### ISSUE TITLE
Adding Flags to filter for Managed Package vs All Components 

### ISSUE THREAD

**Issue by kaulonline** [takahitomiyamoto/salesforce-manifest-generator#2]
Hey,

Thanks for putting this solution. While looking at the solution , I was wondering if you could also include flags to filter the following -

1) Managed Package
2) UnManaged Package
3) All Components

I was wondering if these options could be added, this would be of great help.

Appreciate your efforts in putting this together and sharing further on a global community.

Thanks,
Ashish

**Comment by takahitomiyamoto** [comment]
@kaulonline  I'm sorry, I could not check this for a while. OK, I will check the Metadata API document whether we can do it.

**Comment by LinThaw** [comment]
please add proxy,
<sample>
`    private static LoginResult loginToSalesforce(final String username, final String password, final String authEndPoint)
      throws ConnectionException {
        final ConnectorConfig config = new ConnectorConfig();
      	config.setProxy(CommonUtils.proxyHostname, CommonUtils.proxyPort);
        config.setAuthEndpoint(authEndPoint);
        config.setServiceEndpoint(authEndPoint);
        config.setManualLogin(true);

        final PartnerConnection partnerConnection = new PartnerConnection(config);
        return partnerConnection.login(username, password);
    }

    private static MetadataConnection createMetadataConnection(final LoginResult loginResult)
      throws ConnectionException {
        final ConnectorConfig config = new ConnectorConfig();
      	config.setProxy(CommonUtils.proxyHostname, CommonUtils.proxyPort);
        config.setServiceEndpoint(loginResult.getMetadataServerUrl());
        config.setSessionId(loginResult.getSessionId());

        final MetadataConnection metadataConnection = new MetadataConnection(config);
        return metadataConnection;
    }`

**Comment by LinThaw** [comment]
please add proxy :)
`config.setProxy(CommonUtils.proxyHostname, CommonUtils.proxyPort);
config.setAuthEndpoint(authEndPoint);`

**Comment by takahitomiyamoto** [comment]
@LinThaw Please create new another issue about setProxy. I believe that this is another problem.

**Comment by takahitomiyamoto** [comment]
@kaulonline I found how to resolve your issue. We can check the value of "manageableState", such as "null" or "installed" or "unmanaged". I will try later.

[FileProperties - manageableState](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieveresult.htm#retrieveresult_fileproperties_title)

**Comment by takahitomiyamoto** [comment]
@kaulonline 
I've done. Please verify this issue with v0.3.0.
https://github.com/takahitomiyamoto/salesforce-manifest-generator/releases/tag/v0.3.0

**Comment by kaulonline** [comment]
> @kaulonline
> I've done. Please verify this issue with v0.3.0.
> https://github.com/takahitomiyamoto/salesforce-manifest-generator/releases/tag/v0.3.0

Thanks @takahitomiyamoto ! The solution works. I have another enhancement in mind may be I'll open up a different issue so you can probably assess the feasibility.
