### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by LinThaw** [takahitomiyamoto/salesforce-manifest-generator#3]
@takahitomiyamoto 

please add proxyHostname and proxyPort to credentials.json.
current version need to add proxy logic in following two function and build.
- loginToSalesforce
- createMetadataConnection
<sample code>
config.setProxy(CommonUtils.proxyHostname, CommonUtils.proxyPort); config.setAuthEndpoint(authEndPoint);

Thanks

**Comment by takahitomiyamoto** [comment]
@LinThaw 
I've done. Please verify this issue with v0.3.0.
https://github.com/takahitomiyamoto/salesforce-manifest-generator/releases/tag/v0.3.0
