### ISSUE TITLE
Tool retrieves only folder reports but not reports

### ISSUE THREAD

**Issue by DarkSkull91** [takahitomiyamoto/salesforce-manifest-generator#5]
Hi Takahito, your tool is awsome! I would notify you a possible bug: for the **Report** metadata type, the tool writes only the folder report, but not the report itself.

The AS-IS produces a package.xml like this:
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  ...
  <types>
    <members>folder1</members>
    <members>folder2</members>
    <members>folder3</members>
    <name>Report</name>
  </types>
  ...
  <version>44.0</version>
</Package>`

The TO-BE should be like this:

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  ...
  <types>
    <members>folder1</members>
    <members>folder2</members>
    <members>folder2/report1</members>
    <members>folder2/report2</members>
    <members>folder3/report1</members>
    <name>Report</name>
  </types>
  ...
  <version>44.0</version>
</Package>`

Could you update your tool in that way?

Thanks in advance.

**Comment by takahitomiyamoto** [comment]
@DarkSkull91 
Thank you, sorry for my delay response. I will check it this weekend.

**Comment by takahitomiyamoto** [comment]
@DarkSkull91 
Please check new version:
https://github.com/takahitomiyamoto/salesforce-manifest-generator/releases/tag/v0.4.0

**Comment by DarkSkull91** [comment]
Thank you very much!
