### ISSUE TITLE
Missing retrieve of External Objects and Platform Event

### ISSUE THREAD

**Issue by DarkSkull91** [takahitomiyamoto/salesforce-manifest-generator#7]
Hi takahitomiyamoto,

I'm continuing to use your wonderful tool and I noticed that it doesn't retrieve External Objects and Platform Event, in the package.xml are both under CustomObjects and they last respectively with __x and __e.

Could you add the possibility to retrieve also this kind of Custom Objects, please?

Thanks.

**Comment by takahitomiyamoto** [comment]
Hi @DarkSkull91 
Sorry for the late reply. I try to reproduce this, but I can't. Let me close this issue.

1. I created an external object "Orders__x" and a platform event "Cloud_News__e".
1. I executed my tool.
1. I checked package.xml. --> I can find "Orders__x" and "Cloud_News__e" in it.
